{
 "title": "IIoT DHT11",
 "tags": [
  "iiot",
  "mqtt",
  "dht11"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(bucket: \"iiot\", tag: \"sensor_id\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iiot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"reading\")\n  |> filter(fn: (r) => r.unit == \"°C\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)"
    }
   ]
  },
  {
   "title": "Latest Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iiot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"reading\")\n  |> filter(fn: (r) => r.unit == \"%\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)"
    }
   ]
  },
  {
   "title": "Temperature (last 6h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"iiot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"reading\")\n  |> filter(fn: (r) => r.unit == \"°C\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity (last 6h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"iiot\")\n  |> range(start: -6h)\n  |> filter(fn: (r) => r._measurement == \"reading\")\n  |> filter(fn: (r) => r.unit == \"%\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}